# Generated by Django 3.1.2 on 2020-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201114_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('NO', 'None')], default='NO', max_length=10),
        ),
    ]
