# Generated by Django 3.1.2 on 2020-11-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201114_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
