# Generated by Django 3.1.2 on 2020-10-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quizes', models.ManyToManyField(to='main.Quiz')),
                ('students', models.ManyToManyField(to='main.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
