# Generated by Django 3.1.2 on 2020-10-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_data',
            new_name='submission_date',
        ),
    ]
