# Generated by Django 3.1.2 on 2020-10-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main.submission'),
        ),
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(null=True, related_name='section', to='main.Student'),
        ),
    ]
